### ISSUE TITLE
master → mainにブランチ名変更

### ISSUE THREAD

**Issue by pineapplehunter** [xd-tech/linux-blog#73]
@AstPy-ms 
奴隷制度に関連するワードをテクノレジ業界で使うのをやめようという動きがあるらしく、そのなかでもGitのブランチでmasterをmainに変えるという動きがあるらしい。

やってみる？

**Comment by AstPy-ms** [comment]
わんちゃんある

**Comment by AstPy-ms** [comment]
masterブランチがmainになるだけでブランチ操作とかがそのままなら全く問題ない
やろう

**Comment by pineapplehunter** [comment]
オッケー

**Comment by pineapplehunter** [comment]
変更しておいた。不具合が起きたら教えて。

master → mainにデフォルトのブランチ名の変更
netlifyのチェックするブランチをmaster → mainに変更

**Comment by AstPy-ms** [comment]
:ok_hand:
