### ISSUE TITLE
4d30f5d について

### ISSUE THREAD

**Issue by AstPy-ms** [xd-tech/linux-blog#75]
commit and merge ありがとう。
今回 commitされた **.github/workflow** みたいなやつって何？:thinking:

**Comment by AstPy-ms** [comment]
あと記事の修正しても大丈夫？
ブランチは分けるけど問題あったら教えて

**Comment by AstPy-ms** [comment]
@pineapplehunter

**Comment by pineapplehunter** [comment]
@AstPy-ms 
プルリクにもう少し情報を書いておけばよかったかな

Github Actionsっていう機能で、俺も最近知ったばっかりなんだけど、PushさてたときとかPullrequestが来たときに自動でなにかチャックしたり、テストしたり、ビルドしたりできる面白いツールだよ。

今回はMarkdownのメタデータの部分を表記揺れがないかチェックするために導入してみた

**Comment by pineapplehunter** [comment]
記事は追加して大丈夫だよ。
もう一個追加のチェックが走るようになるはずだけどほとんど気にしないでいいと思う

**Comment by AstPy-ms** [comment]
Gotcha
